"""Build agent/briefing-2026-06-15.json (Day 108 deal-era catch-up), EN + FA.
All event URLs are from the cited intel sweep — no invented URLs."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "agent" / "briefing-2026-06-15.json"

EVENTS = [
    dict(headline="US and Iran reach framework deal to end the war and reopen the Strait of Hormuz",
         source_name="NBC News",
         url="https://www.nbcnews.com/news/us-news/deal-reached-united-states-iran-war-rcna350039",
         published_at="2026-06-14T20:00:00+00:00", public_safe=True,
         summary="Framework MOU halts fighting on all fronts including Lebanon, lifts the US naval blockade, and reopens Hormuz toll-free; formal signing set for June 19 in Switzerland."),
    dict(headline="Trump says Strait of Hormuz reopening, naval blockade lifted as US-Iran deal announced",
         source_name="Al Jazeera",
         url="https://www.aljazeera.com/news/2026/6/14/us-iran-ceasefire-deal-announced-trump-says-strait-of-hormuz-reopening",
         published_at="2026-06-14T18:30:00+00:00", public_safe=True,
         summary="Trump authorized the toll-free opening of Hormuz and immediate removal of the naval blockade; Iran's Deputy FM Gharibabadi confirmed the agreement."),
    dict(headline="Stock markets soar, oil falls as US and Iran confirm deal to end war",
         source_name="Al Jazeera",
         url="https://www.aljazeera.com/economy/2026/6/15/stock-markets-soar-oil-falls-as-us-iran-confirm-deal-to-end-war",
         published_at="2026-06-15T09:00:00+00:00", public_safe=True,
         summary="Brent slid to a two-month low near $84 and the Iranian rial strengthened toward 1.62 million per dollar as markets priced the off-ramp."),
    dict(headline="US rejects Iranian claims on frozen funds under the deal",
         source_name="Iran International",
         url="https://www.iranintl.com/en/202606159822",
         published_at="2026-06-15T12:00:00+00:00", public_safe=True,
         summary="A senior US official called Iran's $24 billion frozen-asset claim 'spin'; the deal is pay-for-performance with no funds released before Iran implements commitments."),
    dict(headline="Iran announces funeral and burial dates for late Supreme Leader Ali Khamenei",
         source_name="Al Jazeera",
         url="https://www.aljazeera.com/news/2026/6/13/iran-announces-funeral-burial-dates-for-late-supreme-leader-khamenei",
         published_at="2026-06-13T15:00:00+00:00", public_safe=True,
         summary="The state funeral for the slain leader is set for July 4-9; his successor and son Mojtaba Khamenei remains out of public view."),
    dict(headline="UN watchdog and Western nations call on Iran to restart nuclear cooperation",
         source_name="Al Jazeera",
         url="https://www.aljazeera.com/news/2026/6/8/un-watchdog-western-nations-call-on-iran-to-restart-nuclear-cooperation",
         published_at="2026-06-08T16:00:00+00:00", public_safe=True,
         summary="IAEA chief Grossi urged Iran to re-engage with inspections while the West sought the whereabouts of its roughly 440kg 60%-enriched uranium stockpile — issues deferred to the 60-day talks."),
    dict(headline="US national gasoline average falls to about $4.07 as the war premium unwinds",
         source_name="AAA Gas Prices",
         url="https://gasprices.aaa.com/",
         published_at="2026-06-15T10:00:00+00:00", public_safe=True,
         summary="Pump prices retraced for a third straight week from a Memorial-Day peak of $4.564, after holding above $4.50 for weeks in May."),
    dict(headline="US generic ballot hits D+6.6 as the Iran war winds down",
         source_name="Silver Bulletin",
         url="https://www.natesilver.net/p/generic-ballot-average-2026-nate-silver-bulletin-congress-polls",
         published_at="2026-06-14T14:00:00+00:00", public_safe=True,
         summary="Polymarket prices a Democratic House at about 83% and Republicans about 56% to hold the Senate, near 2018 levels."),
    dict(headline="Iran's internet roughly 86% restored after an 88-day blackout",
         source_name="Iran International",
         url="https://www.iranintl.com/en/202605251140",
         published_at="2026-05-26T08:00:00+00:00", public_safe=True,
         summary="Connectivity returned in late May, though major social-media platforms remain blocked."),
]

MOVERS = [
    dict(qid="A1", direction="up", delta_pp=73, old=20, new=93,
         why="US-Iran framework deal reached June 14, with formal signing set for June 19 in Switzerland",
         citation_url="https://www.nbcnews.com/news/us-news/deal-reached-united-states-iran-war-rcna350039",
         public_safe=True),
    dict(qid="A2", direction="up", delta_pp=58, old=22, new=80,
         why="Trump ordered the naval blockade lifted and the Strait of Hormuz reopened toll-free",
         citation_url="https://www.aljazeera.com/news/2026/6/14/us-iran-ceasefire-deal-announced-trump-says-strait-of-hormuz-reopening",
         public_safe=True),
    dict(qid="D1", direction="down", delta_pp=38, old=68, new=30,
         why="the rial strengthened toward 1.62 million on the deal, moving away from the 2-million threshold",
         citation_url="https://alanchand.com/en/currencies-price/usd",
         public_safe=True),
    dict(qid="D4", direction="down", delta_pp=12, old=20, new=8,
         why="Brent oil fell to a two-month low as the deal set Hormuz to reopen",
         citation_url="https://www.aljazeera.com/economy/2026/6/15/stock-markets-soar-oil-falls-as-us-iran-confirm-deal-to-end-war",
         public_safe=True),
    dict(qid="E2", direction="up", delta_pp=23, old=60, new=83,
         why="the generic ballot at D+6.6 and Polymarket's Democratic House price keep a chamber flip the favorite",
         citation_url="https://www.natesilver.net/p/generic-ballot-average-2026-nate-silver-bulletin-congress-polls",
         public_safe=True),
]

EVENTS_FA = [
    dict(headline="آمریکا و ایران به توافق چارچوبی برای پایان جنگ و بازگشایی تنگه‌ی هرمز رسیدند",
         source_name="ان‌بی‌سی", url=EVENTS[0]["url"], published_at=EVENTS[0]["published_at"], public_safe=True,
         summary="تفاهم‌نامه‌ی چارچوبی جنگ را در همه‌ی جبهه‌ها از جمله لبنان متوقف می‌کند، محاصره‌ی دریایی آمریکا را برمی‌دارد و هرمز را بدون عوارض بازمی‌گشاید؛ امضای رسمی ۱۹ ژوئن در سوئیس."),
    dict(headline="ترامپ: تنگه‌ی هرمز بازگشایی می‌شود و محاصره‌ی دریایی برداشته شد",
         source_name="الجزیره", url=EVENTS[1]["url"], published_at=EVENTS[1]["published_at"], public_safe=True,
         summary="ترامپ بازگشایی بدون‌عوارض هرمز و حذف فوری محاصره‌ی دریایی را تأیید کرد؛ قریب‌آبادی معاون وزیر خارجه‌ی ایران توافق را تأیید کرد."),
    dict(headline="بازارها صعود کردند و نفت افت کرد در پی تأیید توافق پایان جنگ از سوی آمریکا و ایران",
         source_name="الجزیره", url=EVENTS[2]["url"], published_at=EVENTS[2]["published_at"], public_safe=True,
         summary="برنت به کمترین دو ماه نزدیک ۸۴ دلار رسید و ریال ایران به سمت ۱.۶۲ میلیون تقویت شد."),
    dict(headline="آمریکا ادعاهای ایران درباره‌ی دارایی‌های مسدود را رد کرد",
         source_name="ایران اینترنشنال", url=EVENTS[3]["url"], published_at=EVENTS[3]["published_at"], public_safe=True,
         summary="یک مقام ارشد آمریکایی ادعای ۲۴ میلیارد دلاری ایران را «جوسازی» خواند؛ توافق پرداخت در ازای عملکرد است."),
    dict(headline="ایران تاریخ تشییع و خاک‌سپاری رهبر فقید علی خامنه‌ای را اعلام کرد",
         source_name="الجزیره", url=EVENTS[4]["url"], published_at=EVENTS[4]["published_at"], public_safe=True,
         summary="مراسم تشییع رهبر کشته‌شده ۴ تا ۹ ژوئیه است؛ جانشین و پسرش مجتبی خامنه‌ای همچنان از دید عمومی پنهان است."),
    dict(headline="آژانس و کشورهای غربی از ایران خواستند همکاری هسته‌ای را از سر بگیرد",
         source_name="الجزیره", url=EVENTS[5]["url"], published_at=EVENTS[5]["published_at"], public_safe=True,
         summary="گروسی از ایران خواست بازرسی‌ها را از سر بگیرد؛ پرونده‌ی ذخیره‌ی حدود ۴۴۰ کیلوگرمی اورانیوم ۶۰٪ به مذاکرات ۶۰ روزه موکول شد."),
    dict(headline="میانگین ملی بنزین آمریکا با فروکش حق بیمه‌ی جنگ به حدود ۴.۰۷ دلار افت کرد",
         source_name="AAA", url=EVENTS[6]["url"], published_at=EVENTS[6]["published_at"], public_safe=True,
         summary="قیمت بنزین برای سومین هفته‌ی پیاپی از سقف ۴.۵۶۴ دلاری روز یادبود پایین آمد، پس از هفته‌ها ماندن بالای ۴.۵۰ دلار در مه."),
    dict(headline="رأی عمومی کنگره‌ی آمریکا با فروکش جنگ ایران به D+6.6 رسید",
         source_name="سیلور بولتن", url=EVENTS[7]["url"], published_at=EVENTS[7]["published_at"], public_safe=True,
         summary="پلی‌مارکت مجلس نمایندگان را با حدود ۸۳٪ برای دموکرات‌ها و سنا را با حدود ۵۶٪ برای جمهوری‌خواهان قیمت‌گذاری می‌کند."),
    dict(headline="اینترنت ایران پس از ۸۸ روز قطعی حدود ۸۶٪ بازگشت",
         source_name="ایران اینترنشنال", url=EVENTS[8]["url"], published_at=EVENTS[8]["published_at"], public_safe=True,
         summary="اتصال در اواخر مه بازگشت، هرچند شبکه‌های اجتماعی بزرگ همچنان مسدودند."),
]

MOVERS_FA = [
    dict(qid="A1", direction="up", delta_pp=73, old=20, new=93,
         why="توافق چارچوبی ایران و آمریکا در ۱۴ ژوئن حاصل شد و امضای رسمی برای ۱۹ ژوئن تعیین شد",
         citation_url=MOVERS[0]["citation_url"], public_safe=True),
    dict(qid="A2", direction="up", delta_pp=58, old=22, new=80,
         why="ترامپ دستور رفع محاصره‌ی دریایی و بازگشایی بدون‌عوارض تنگه‌ی هرمز را داد",
         citation_url=MOVERS[1]["citation_url"], public_safe=True),
    dict(qid="D1", direction="down", delta_pp=38, old=68, new=30,
         why="ریال با توافق به سمت ۱.۶۲ میلیون تقویت شد و از آستانه‌ی ۲ میلیون دور شد",
         citation_url=MOVERS[2]["citation_url"], public_safe=True),
    dict(qid="D4", direction="down", delta_pp=12, old=20, new=8,
         why="نفت برنت با بازگشایی هرمز در توافق به کمترین دو ماه افت کرد",
         citation_url=MOVERS[3]["citation_url"], public_safe=True),
    dict(qid="E2", direction="up", delta_pp=23, old=60, new=83,
         why="رأی عمومی D+6.6 و قیمت پلی‌مارکت برای مجلس دموکرات، تغییر کنترل یک مجلس را نامزد اصلی نگه می‌دارد",
         citation_url=MOVERS[4]["citation_url"], public_safe=True),
]

briefing = {
    "tick_date": "2026-06-15",
    "tick_timestamp_utc": "2026-06-15T11:00:00+00:00",
    "day_number": 108,
    "cron_status": "ok",
    "events_count_24h": len(EVENTS),
    "probability_moves_24h": len(MOVERS),
    "briefing_partial": False,
    "en": {
        "read_paragraphs": [
            "Day 108 is the day the war ends on paper. On June 14 the US and Iran announced a framework deal — Trump called it 'complete,' Iran's Deputy FM Gharibabadi confirmed it — that halts the fighting on all fronts including Lebanon, lifts the US naval blockade, and reopens the Strait of Hormuz toll-free, with a formal signing set for June 19 in Switzerland and a 60-day window to negotiate a permanent settlement. Markets moved first: Brent slid to a two-month low near $84, US pump prices fell back to about $4.07, and the rial strengthened toward 1.62 million. It is the largest single shift since this dashboard began.",
            "The update also corrects the record. The dashboard had been carrying a counterfactual on Iran's leadership: Ali Khamenei was not 'recovering from burns' — he was killed in the Feb 28 strikes, and his son Mojtaba has led Iran since March 8 (Ali's state funeral is now set for July 4-9). That resolves the two leadership questions YES, alongside six others the war already settled — US strikes on Iran (B1), Iran's strikes on US bases (B2), Israel's strike on Natanz (B3), a third vessel seizure (B5), oil exports below 0.5M bpd (D2), and US gas above $4.50 for weeks (D3). Nine cards are now marked Resolved.",
            "What's still live is implementation, not escalation. The political deal is fastest; physical Hormuz traffic (about 2-6 ships/day in mid-June) lags on a weeks-to-months mine-clearing timeline; and the hardest file — enrichment, Iran's ~440kg 60%-enriched stockpile, sanctions relief, and a disputed $24B in frozen assets the US calls pay-for-performance — is deferred to the 60-day talks. Watch the June 19 signing, whether the ceasefire holds (B6), and whether the framework hardens into a permanent settlement by September (A6, roughly even).",
        ],
        "movers": MOVERS,
        "events": EVENTS,
    },
    "fa": {
        "read_paragraphs": [
            "روز ۱۰۸ روزی است که جنگ روی کاغذ پایان می‌یابد. در ۱۴ ژوئن آمریکا و ایران یک توافق چارچوبی اعلام کردند — ترامپ آن را «کامل» خواند و قریب‌آبادی معاون وزیر خارجه‌ی ایران تأیید کرد — که جنگ را در همه‌ی جبهه‌ها از جمله لبنان متوقف می‌کند، محاصره‌ی دریایی آمریکا را برمی‌دارد و تنگه‌ی هرمز را بدون عوارض بازمی‌گشاید، با امضای رسمی در ۱۹ ژوئن در سوئیس و پنجره‌ی ۶۰ روزه برای مذاکره‌ی تسویه‌ی دائمی. بازارها اول حرکت کردند: برنت به کمترین دو ماه نزدیک ۸۴ دلار رسید، بنزین آمریکا به حدود ۴.۰۷ دلار بازگشت و ریال به سمت ۱.۶۲ میلیون تقویت شد. این بزرگ‌ترین جابه‌جایی از آغاز این داشبورد است.",
            "این به‌روزرسانی، رکورد را هم تصحیح می‌کند. داشبورد درباره‌ی رهبری ایران یک خلاف‌واقع را حمل می‌کرد: علی خامنه‌ای «در حال بهبود از سوختگی» نبود — او در حملات ۲۸ فوریه کشته شد و پسرش مجتبی از ۸ مارس ایران را رهبری می‌کند (مراسم تشییع علی اکنون ۴ تا ۹ ژوئیه است). این دو پرسش رهبری را بله می‌کند، در کنار شش پرسش دیگری که جنگ پیشتر قطعی کرده بود — حملات آمریکا به ایران (B1)، حملات ایران به پایگاه‌های آمریکا (B2)، حمله‌ی اسرائیل به نطنز (B3)، توقیف سومین کشتی (B5)، صادرات نفت زیر ۰.۵ میلیون بشکه (D2)، و بنزین آمریکا بالای ۴.۵۰ دلار برای هفته‌ها (D3). اکنون نه کارت «قطعی‌شده» نشان دارند.",
            "آنچه هنوز زنده است، اجراست نه تشدید. توافق سیاسی سریع‌ترین است؛ تردد فیزیکی هرمز (حدود ۲ تا ۶ کشتی در روز در میانه‌ی ژوئن) با مین‌روبی در بازه‌ی هفته‌تا‌ماه عقب می‌ماند؛ و سخت‌ترین پرونده — غنی‌سازی، ذخیره‌ی حدود ۴۴۰ کیلوگرمی اورانیوم ۶۰٪، رفع تحریم و ۲۴ میلیارد دلار دارایی مسدودِ مورد مناقشه که آمریکا آن را پرداخت در ازای عملکرد می‌خواند — به مذاکرات ۶۰ روزه موکول شده. امضای ۱۹ ژوئن، دوام آتش‌بس (B6) و سفت‌شدن چارچوب به تسویه‌ی دائمی تا سپتامبر (A6، تقریباً پنجاه‌پنجاه) را پایید.",
        ],
        "movers": MOVERS_FA,
        "events": EVENTS_FA,
    },
}

OUT.write_text(json.dumps(briefing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("wrote", OUT, "| events:", len(EVENTS), "| movers:", len(MOVERS))
